### ISSUE TITLE
plz add me to images translation

### ISSUE THREAD

**Issue by pachamaltese** [cienciadedatos/descripcion-y-orientaciones#17]
Hi @rivaquiroga 
I have translated most diagrams, please add me here https://github.com/cienciadedatos/descripcion-y-orientaciones/blob/master/distribucion-roles.md
Thanks!!

**Comment by raynamharris** [comment]
See #18

**Comment by raynamharris** [comment]
Quick question, have you started uploading the translated images? I'm curious to see them. They would be great resources to share on Twitter and elsewhere for people to use in talks, etc. I wonder if it would be good to create an issue(s) where images could be commented on before final approval

**Comment by pachamaltese** [comment]
@raynamharris Hi! yes, here are all the diagrams https://github.com/pachamaltese/r4ds/tree/traduccion/diagrams
provided I don't have a Mac nor Omigraffle, I re-built all the diagrams using Inkscape that is open, multi platform, and SVG compatible
those diagrams are also compatible with Wikipedia SVG standard and other, and can be edited right away to translate the texts inside them to other languages

**Comment by pachamaltese** [comment]
@raynamharris Hi! I've just included OTP (object to path) versions of all diagrams, these are not so editable but they shall work wherever you put them with or without the fonts, for allow full edition I kept the original Inkscape version with text included as text
